export const FirstData= [
    
    {
        SN: "1",
        scrip: "AKPL",
        currentBalance: "113.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "113.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "2",
        Scrip: "ALBSL",
        CurrentBalance: "18.0",
        PledgeBalance: "0.0",
        LockinBalance: "0.0",
        FreezeBalance: "0.0",
        FreeBalance: "18.0",
        DematPending: "0.0",
        Remarks: " "
    },
    {
        SN: "3",
        Scrip: "API",
        CurrentBalance: "547.0",
        PledgeBalance: "0.0",
        LockinBalance: "0.0",
        FreezeBalance: "0.0",
        FreeBalance: "547.0",
        DematPending: "0.0",
        Remarks: " "
    },
    {
        SN: "4",
        Scrip: "BARUN",
        CurrentBalance: "2.0",
        PledgeBalance: "0.0",
        LockinBalance: "0.0",
        FreezeBalance: "0.0",
        FreeBalance: "2.0",
        DematPending: "0.0",
        Remarks: " "
    },
    {
        SN: "5",
        Scrip: "BEDC",
        CurrentBalance: "5.0",
        PledgeBalance: "0.0",
        LockinBalance: "0.0",
        FreezeBalance: "0.0",
        FreeBalance: "5.0",
        DematPending: "0.0",
        Remarks: " "
    },
    {
        SN: "6",
        Scrip: "BGWT",
        CurrentBalance: "10.0",
        PledgeBalance: "0.0",
        LockinBalance: "0.0",
        FreezeBalance: "0.0",
        FreeBalance: "10.0",
        DematPending: "0.0",
        Remarks: " "
    },
    { 
        SN: "7",
        scrip: "GBLBS",
        currentBalance: "45.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "45.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "8",
        scrip: "GHL",
        currentBalance: "100.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "100.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "9",
        scrip: "HDHPC",
        currentBalance: "200.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "200.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "10",
        scrip: "HLBSL",
        currentBalance: "2.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "2.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "11",
        scrip: "HLI",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "12",
        scrip: "HPPL",
        currentBalance: "201.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "201.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "13",
        scrip: "LEC",
        currentBalance: "310.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "310.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "14",
        scrip: "MBJC",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "15",
        scrip: "MERO",
        currentBalance: "183.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "183.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "16",
        scrip: "NABIL",
        currentBalance: "100.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "100.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "17",
        scrip: "NGPL",
        currentBalance: "40.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "40.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "18",
        scrip: "NICLBSL",
        currentBalance: "36.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "36.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "19",
        scrip: "NIFRA",
        currentBalance: "238.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "238.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "20",
        scrip: "NIMB",
        currentBalance: "329.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "329.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "21",
        scrip: "NLIC",
        currentBalance: "129.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "129.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "22",
        scrip: "NRIC",
        currentBalance: "51.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "51.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "23",
        scrip: "NRN",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "24",
        scrip: "NUBL",
        currentBalance: "298.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "298.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "25",
        scrip: "PHCL",
        currentBalance: "560.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "560.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "26",
        scrip: "RADHI",
        currentBalance: "76.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "76.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "27",
        scrip: "RHPL",
        currentBalance: "310.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "310.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "28",
        scrip: "SAHAS",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "29",
        scrip: "SDLBSL",
        currentBalance: "17.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "17.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "30",
        scrip: "SGIC",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "31",
        scrip: "SIFC",
        currentBalance: "11.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "11.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "32",
        scrip: "SJCL",
        currentBalance: "180.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "180.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "33",
        scrip: "SJLIC",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "34",
        scrip: "SPDL",
        currentBalance: "183.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "183.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "35",
        scrip: "SRLI",
        currentBalance: "10.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "10.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "36",
        scrip: "SWMF",
        currentBalance: "174.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "174.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "37",
        scrip: "UAIL",
        currentBalance: "9.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "9.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "38",
        scrip: "UMHL",
        currentBalance: "53.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "53.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "39",
        scrip: "UPCL",
        currentBalance: "1085.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "1085.0",
        dematPending: "0.0",
        remarks: " "
    },
    {
        SN: "40",
        scrip: "UPPER",
        currentBalance: "530.0",
        pledgeBalance: "0.0",
        lockinBalance: "0.0",
        freezeBalance: "0.0",
        freeBalance: "530.0",
        dematPending: "0.0",
        remarks: " "
    }

]